/* tslint:disable */
/* eslint-disable */
/**
 * elkar-app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebuggerHistoryResponse
 */
export interface DebuggerHistoryResponse {
    /**
     * 
     * @type {string}
     * @memberof DebuggerHistoryResponse
     */
    id: string;
    /**
     * 
     * @type {any}
     * @memberof DebuggerHistoryResponse
     */
    payload: any | null;
    /**
     * 
     * @type {string}
     * @memberof DebuggerHistoryResponse
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof DebuggerHistoryResponse
     */
    url: string;
}

/**
 * Check if a given object implements the DebuggerHistoryResponse interface.
 */
export function instanceOfDebuggerHistoryResponse(value: object): value is DebuggerHistoryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function DebuggerHistoryResponseFromJSON(json: any): DebuggerHistoryResponse {
    return DebuggerHistoryResponseFromJSONTyped(json, false);
}

export function DebuggerHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebuggerHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'payload': json['payload'],
        'taskId': json['task_id'],
        'url': json['url'],
    };
}

export function DebuggerHistoryResponseToJSON(json: any): DebuggerHistoryResponse {
    return DebuggerHistoryResponseToJSONTyped(json, false);
}

export function DebuggerHistoryResponseToJSONTyped(value?: DebuggerHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'payload': value['payload'],
        'task_id': value['taskId'],
        'url': value['url'],
    };
}

