/* tslint:disable */
/* eslint-disable */
/**
 * elkar-app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreA2ADebuggerHistoryInput
 */
export interface StoreA2ADebuggerHistoryInput {
    /**
     * 
     * @type {any}
     * @memberof StoreA2ADebuggerHistoryInput
     */
    payload: any | null;
    /**
     * 
     * @type {string}
     * @memberof StoreA2ADebuggerHistoryInput
     */
    url: string;
}

/**
 * Check if a given object implements the StoreA2ADebuggerHistoryInput interface.
 */
export function instanceOfStoreA2ADebuggerHistoryInput(value: object): value is StoreA2ADebuggerHistoryInput {
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function StoreA2ADebuggerHistoryInputFromJSON(json: any): StoreA2ADebuggerHistoryInput {
    return StoreA2ADebuggerHistoryInputFromJSONTyped(json, false);
}

export function StoreA2ADebuggerHistoryInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreA2ADebuggerHistoryInput {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'],
        'url': json['url'],
    };
}

export function StoreA2ADebuggerHistoryInputToJSON(json: any): StoreA2ADebuggerHistoryInput {
    return StoreA2ADebuggerHistoryInputToJSONTyped(json, false);
}

export function StoreA2ADebuggerHistoryInputToJSONTyped(value?: StoreA2ADebuggerHistoryInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
        'url': value['url'],
    };
}

