name: Python CI

on:
  push:
    paths:
      - "src/elkar/**/*.py"
      - "tests/**/*.py"
      - "pyproject.toml"
      - ".github/workflows/python-ci.yml"
  pull_request:
    paths:
      - "src/elkar/**/*.py"
      - "tests/**/*.py"
      - "pyproject.toml"
      - ".github/workflows/python-ci.yml"

jobs:
  python-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install .
          uv pip install ruff mypy pytest

      - name: Lint with ruff
        run: ruff check src/elkar

      - name: Type check with mypy
        run: mypy src/elkar

      - name: Run tests with pytest
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: pytest
